#!/usr/bin/perl
use 5.006;
use strict;
use warnings;

use Language::Bel::Globals::FastFuncs::Preprocessor qw(
    generate_target_file
);

binmode STDOUT, ':encoding(utf-8)';

generate_target_file();

