#!/usr/bin/perl
use 5.006;
use strict;
use warnings;

use File::Temp qw(tempfile);

use Language::Bel::Globals::Generator qw(generate_globals);

binmode STDOUT, ':encoding(utf-8)';

my (undef, $filename) = tempfile();
END { unlink $filename }

my $status = system(
    "perl -T -Ilib t/00-consistent-fastfunc-exports.t " .
    "> $filename 2>&1 > $filename"
);

if ($status != 0) {
    system("cat $filename");
    die "Aborting due to failed consistency test\n";
}

$status = system(
    "perl -T -Ilib t/00-consistent-fastoperative-exports.t " .
    "> $filename 2>&1 > $filename"
);

if ($status != 0) {
    system("cat $filename");
    die "Aborting due to failed consistency test\n";
}

my $bel = Language::Bel->new({ output => sub {} });

my $generated_globals;
do {
    local *STDOUT;
    open(STDOUT, ">>", \$generated_globals)
        or die "failed to open file handle to string ($!)\n";

    generate_globals($bel);     # will print into $generated_globals
};

my $globals_path = "lib/Language/Bel/Globals.pm";

open(my $GLOBALS, ">", $globals_path)
    or die "Couldn't open $globals_path: $!";

print {$GLOBALS} $generated_globals;

close($GLOBALS);

